#pragma once

#include "CoreMinimal.h"
#include "UObject/ObjectMacros.h"
#include "Engine/EngineTypes.h"
#include "MIsActiveCheckerComponent.generated.h"

DECLARE_DELEGATE(FOnDisabled);
DECLARE_DELEGATE(FOnEnabled);

USTRUCT()
struct FDisabledComponentInfo
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UActorComponent* Component;

	bool bCanEverTick = false;
};

UCLASS(BlueprintType, meta=(BlueprintSpawnableComponent, IgnoreCategoryKeywordsInSubclasses, ShortTooltip="A component that tuns on/off entie object. For example when the object was culled"))
class TOPDOWNTEMP_API UMIsActiveCheckerComponent : public UActorComponent
{
	GENERATED_UCLASS_BODY()

public:
	bool GetIsActive() const { return bIsOwnerActive; }

	class UPrimitiveComponent* GetPrimitive() const { return CollisionPrimitive; }
	
	void DisableOwner(bool bForce = false);

	void EnableOwner(bool bForce = false);

	bool GetAlwaysEnabled() const { return bAlwaysEnabled; }

	bool GetPreserveBlockConstancy() const { return bPreserveBlockConstancy; }

	//** Likely to be removed as it is not needed. It finds a UPrimitiveComponent tagged with IsActiveChecker and set it up. Should be called in owner's PostInitializeComponents */
	virtual void SetUpCollisionPrimitive();

	FOnDisabled OnDisabledDelegate;
	FOnEnabled OnEnabledDelegate;

protected:
	//* Determines the bounds of the object. If it doesnt overlap the World active zone, the object is disabled */
	UPROPERTY()
	UPrimitiveComponent* CollisionPrimitive = nullptr;

	/** The owner never stops ticking and remains visible even beyond the frustum. Any engine optimizations/culls still applicable */
	UPROPERTY(Category=Testing, EditDefaultsOnly, BlueprintReadWrite)
	bool bAlwaysEnabled = false;

	/** If true, the block on which the owner is located is not regenerated by the game feature */
	UPROPERTY(Category=Testing, EditDefaultsOnly, BlueprintReadWrite)
	bool bPreserveBlockConstancy = false;

private: // Saved data
	UPROPERTY(VisibleAnywhere)
	bool bIsOwnerActive = true;

	bool bIsOwnerDisabledByForce = false;

	TOptional<bool> bActorWasHiddenInGame;

	TOptional<bool> bActorHadTickEnabled;

	UPROPERTY()
	TArray<FDisabledComponentInfo> DisabledComponentsData;
};